apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cron-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kbot
              image: public.ecr.aws/m4r1g5r3/kbot:8294233-amd64
          restartPolicy: OnFailure
